# Generated by Django 3.2.14 on 2022-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20220710_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='compny',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
